spring.application.name=event-management-service
api.prefix=/event-management-service/v1
server.servlet.context-path=${api.prefix}

# Default profile
spring.profiles.active=dev

# Profile groups for common + environment-specific configs
spring.profiles.group.dev=dev,common
spring.profiles.group.test=test,common
spring.profiles.group.prod=prod,common