security.jwt.secret=dev-secret-change-me

# Local PostgreSQL (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db?currentSchema=event_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=event_db