# common properties
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.client-id=${KAFKA_PRODUCER_CLIENT_ID:event-management-service}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topics.event-published=${KAFKA_TOPIC_EVENT_PUBLISHED:inventory-init.v1}